language: minimal
sudo: required
if: branch = master
services:
  - docker
env:
  global: 
    - IMAGE_NAME=frontend
    - REPO=nicholai.dev
    - REGISTRY_USER=nicholaiii
    - REGISTRY_URL="docker.pkg.github.com/${REGISTRY_USER}/${REPO}/${IMAGE_NAME}"
    - LATEST_REG="$REGISTRY_URL:latest"

before_script:
  - version="$(date +%s)"

script:
  - docker build -t "$IMAGE_NAME" .
