name: Deploy PR to static-deploy

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm i --global @staticdeploy/cli
      - run: npm run build
      - name: Publish bundle to staticdeploy
        run: staticdeploy bundle --from ./public --name nicholai.dev --tag $GITHUB_SHA --description "Build of commit $GITHUB_SHA"
        env:
          STATICDEPLOY_API_URL: ${{ secrets.STATICDEPLOY_API_URL }}
          STATICDEPLOY_API_TOKEN: ${{ secrets.STATICDEPLOY_API_TOKEN }}
      - name: Deploy to staticdeploy
        run: staticdeploy deploy --app nicholai.dev --entrypoint dev.nicholai.dev/$GITHUB_SHA --bundle nicholai.dev:$GITHUB_SHA
        env:
          STATICDEPLOY_API_URL: ${{ secrets.STATICDEPLOY_API_URL }}
          STATICDEPLOY_API_TOKEN: ${{ secrets.STATICDEPLOY_API_TOKEN }}